### PR TITLE
Support pipelining for cluster

### PR DESCRIPTION
**Pull request by larryzhu2018**
There are two changes needed to support cluster mode:
1. instead of asserting on the key slot, we can just check if the server is the same
2. we need to expose the server so that the client can group all the requests for the same server and do pipelines. If there is any key move error, the client should just try again by getting the new key server and and grouping the message accordingly.

### CODE REVIEW

**Comment by mediocregopher** [comment]
Hi @larryzhu2018, this use-case has been brought up before (issue #228 ) and I believe my response remains the same. It's a tricky use-case to fully support while handling all edge-cases (migrations, down nodes, etc...) in a clean way, so it's better left up to the user to determine what they wish to do. You can see my answer in that issue for my specific suggestion.

I'm afraid I can't accept this PR, as the functionality you need is already available and I don't wish to modify or expand radix's API for it. I hope this doesn't stop you from contributing in the future though, just please make an issue first next time so we can discuss the changes before you spend time on it :) 

Thanks!
Brian

**Comment by mediocregopher** [comment]
To address your `AddrForKey` change specifically, that's probably not a good idea to use for what you're trying to do, because it's going to grab an RLock for every key. Presumably you have a lot of keys (otherwise it wouldn't be worth the effort to batch them like this), so you're better off calling Topo and grouping the keys that way.

**Comment by larryzhu2018** [comment]
> Hi @larryzhu2018, this use-case has been brought up before (issue #228 ) and I believe my response remains the same. It's a tricky use-case to fully support while handling all edge-cases (migrations, down nodes, etc...) in a clean way, so it's better left up to the user to determine what they wish to do. You can see my answer in that issue for my specific suggestion.
> 
> I'm afraid I can't accept this PR, as the functionality you need is already available and I don't wish to modify or expand radix's API for it. I hope this doesn't stop you from contributing in the future though, just please make an issue first next time so we can discuss the changes before you spend time on it :)
> 
> Thanks!
> Brian

hi Brian, I read #228 before submitting this PR. as I mentioned in the description, the client should just try again by getting the new key server and and grouping the message accordingly. Does that work?

**Comment by larryzhu2018** [comment]
> To address your `AddrForKey` change specifically, that's probably not a good idea to use for what you're trying to do, because it's going to grab an RLock for every key. Presumably you have a lot of keys (otherwise it wouldn't be worth the effort to batch them like this), so you're better off calling Topo and grouping the keys that way.

these are local operations, right? can you tell me how do you do that? basically I would like to group the keys for the same server. you cannot use key slots to group as that would be too many groups and not enough message to make the pipeline meaningful

**Pull request closed without merging**
