### PR TITLE
Add go-redis benchmark

### PR DESCRIPTION
**Pull request by plasticbox**

### CODE REVIEW

**Comment by mediocregopher** [comment]
He @plasticbox , thanks for the PR! This looks good to me, although I don't know if I'll have the time to run the benches myself in the near future. Have you been able to? I'm curious how radix fairs against go-redis :)

**Comment by kataras** [comment]
A note here: if you do accept PRs with external modules please rename the bench folder to _bench in order for go-get to ignore the deps inside it. @mediocregopher

**Comment by mediocregopher** [comment]
Thanks @kataras , I didn't realize that was an option.

@plasticbox are you still interested in merging this? I guess there was nothing wrong with it, just never heard back so it fell off my radar.

**Comment by mediocregopher** [comment]
I cherry-picked this onto the v4 branch, so it will get included in the next round of benchmarks I do when releasing that. Thanks @plasticbox !

**Comment by plasticbox** [comment]
@mediocregopher I'm so sorry. I couldn't reply because there were a lot of things going on personally.
I just came in to get a hold of myself as the new year is approaching and saw it now
Thank you. Happy new year.

**Pull request closed without merging**
