### PR TITLE
v4: reader can leave read buffer in an inconsistent state

### PR DESCRIPTION
**Pull request by apersson**
Addresses inconsistent issue in #277.

### CODE REVIEW

**Comment by mediocregopher** [comment]
Thanks @apersson ! Great job catching this bug, and thank you for submitting the fix :) One thing before merging: it looks like the ` TestConnDeadlineExceeded` test is no longer passing on your branch (at least, on my local machine). I'm not entirely sure why, I might be able to look into it more soon if you're not able to, but just wanted to point that out as being a blocker before merging.

(Also I'm not sure why the Github Action to do the test didn't run here.... it definitely should have)

**Comment by apersson** [comment]
It's because the test is now hitting the 'partial read' error and the connection is closed. I've updated the test so that it starts with a high timeout (to ensure success) and then reduce it until it hits a timeout.

**Comment by mediocregopher** [comment]
Nice, merged! Hopefully that fixes the last of those inconsistencies you were seeing :pray:

**Comment by apersson** [comment]
Thanks. The number of inconsistencies have dropped further, but are unfortunately still present. I'm going to do a test where the write path is closed right away under all error conditions to see if it resolves the remaining inconsistencies.

However, while testing these changes I encountered another issue: the sequence number logic on the read path does not work with `radix.Pipeline`.

**Pull request merged**
